[package]
name = "aurora-thing"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
chrono = "0.4.42"
regex = "1.11.2"
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
serde = "1.0.225"
serde_json = "1.0.145"
thiserror = "2.0.16"
